language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - cd ./Tests/Resources/
  - unzip people.json.zip
  - cd ../../
  - composer install --prefer-source

script:
  phpunit --bootstrap ./Tests/Unit/Bootstrap.php

#git:
#  depth: 5